import {
  BarChart3,
  Bell,
  Building2,
  LayoutDashboard,
  Landmark,
  LayoutList,
  Laptop,
  Package,
  ReceiptText,
  CalendarClock,
  RotateCcw,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  CircleUser,
  Truck,
  Users,
  Wallet,
  FileText,
  Repeat,
  ClipboardList,
  Boxes,
  HandCoins,
  Coins,
  Siren,
  Upload,
  CreditCard,
  Tag,
  Barcode,
  Receipt,
  Star,
  PieChart,
  Ship,
  type LucideIcon,
} from "lucide-react";
import type { NavSection } from "@/types/navigation";

export const NAV_SECTIONS: NavSection[] = [
  {
    title: "Overview",
    titleAr: "نظرة عامة",
    items: [
      {
        title: "Dashboard",
        titleAr: "لوحة التحكم",
        href: "/app/dashboard",
        icon: LayoutDashboard,
        permission: "dashboard.view",
        keywords: "home overview analytics kpi",
      },
    ],
  },
  {
    title: "Operations",
    titleAr: "العمليات",
    items: [
      {
        title: "Customers",
        titleAr: "العملاء",
        href: "/app/customers",
        icon: Users,
        permission: "customers.view",
        keywords: "clients contacts parties accounts receivable",
      },
      {
        title: "Suppliers",
        titleAr: "الموردون",
        href: "/app/suppliers",
        icon: Truck,
        permission: "suppliers.view",
        keywords: "vendors contacts parties accounts payable",
      },
      {
        title: "Products",
        titleAr: "المنتجات",
        href: "/app/products",
        icon: Package,
        permission: "products.view",
        keywords: "items catalog sku services stock",
      },
      {
        title: "Warehouses",
        titleAr: "المخازن",
        href: "/app/warehouses",
        icon: Building2,
        permission: "warehouses.view",
        keywords: "locations stores storage branches",
      },
      {
        title: "Inventory",
        titleAr: "المخزون",
        href: "/app/inventory",
        icon: LayoutList,
        permission: "inventory.view",
        keywords: "stock levels quantities batches movements",
      },
      {
        title: "Barcodes",
        titleAr: "الباركود",
        href: "/app/barcodes",
        icon: Barcode,
        permission: "barcodes.view",
        keywords: "barcodes barcode generate print scan product labels",
      },
    ],
  },
  {
    title: "Trade",
    titleAr: "التجارة",
    items: [
      {
        title: "Sales",
        titleAr: "المبيعات",
        href: "/app/sales",
        icon: ShoppingBag,
        permission: "sales.view",
        keywords: "invoices orders revenue invoices",
      },
      {
        title: "Purchases",
        titleAr: "المشتريات",
        href: "/app/purchases",
        icon: ShoppingCart,
        permission: "purchases.view",
        keywords: "bills purchase orders expenses",
      },
      {
        title: "Quotes",
        titleAr: "عروض الأسعار",
        href: "/app/quotes",
        icon: FileText,
        permission: "quotes.view",
        keywords: "quotations estimates proposals quotes",
      },
      {
        title: "Recurring",
        titleAr: "الفواتير الدورية",
        href: "/app/recurring",
        icon: Repeat,
        permission: "recurring.view",
        keywords: "subscriptions recurring automatic repeat",
      },
      {
        title: "Notes",
        titleAr: "الإشعارات الدائنة والمدينة",
        href: "/app/notes",
        icon: ReceiptText,
        permission: "notes.view",
        keywords: "credit notes debit notes refunds returns adjustments",
      },
      {
        title: "Purchase Orders",
        titleAr: "أوامر الشراء",
        href: "/app/purchase-orders",
        icon: ClipboardList,
        permission: "purchase-orders.view",
        keywords: "purchase orders approval receive goods po",
      },
      {
        title: "Sales Returns",
        titleAr: "مرتجعات المبيعات",
        href: "/app/sales-returns",
        icon: RotateCcw,
        permission: "sales.view",
        keywords: "sales returns refund items customers",
      },
      {
        title: "Purchase Returns",
        titleAr: "مرتجعات المشتريات",
        href: "/app/purchase-returns",
        icon: RotateCcw,
        permission: "purchases.view",
        keywords: "purchase returns refund items suppliers",
      },
      {
        title: "Price Lists",
        titleAr: "قوائم الأسعار",
        href: "/app/price-lists",
        icon: Tag,
        permission: "products.view",
        keywords: "price lists pricing tiers products",
      },
      {
        title: "Delivery Notes",
        titleAr: "سندات التوريد",
        href: "/app/delivery-notes",
        icon: Truck,
        permission: "purchases.view",
        keywords: "delivery notes receiving goods suppliers",
      },
    ],
  },
  {
    title: "Finance",
    titleAr: "المالية",
    items: [
      {
        title: "Treasury",
        titleAr: "الخزينة",
        href: "/app/treasury",
        icon: Wallet,
        permission: "treasury.view",
        keywords: "bank cash accounts transactions payments",
      },
      {
        title: "Payment Vouchers",
        titleAr: "سندات القبض والصرف",
        href: "/app/payment-vouchers",
        icon: CreditCard,
        permission: "treasury.view",
        keywords: "payment vouchers receipt payment cash",
      },
      {
        title: "Accounting",
        titleAr: "المحاسبة",
        href: "/app/accounting",
        icon: Landmark,
        permission: "accounting.view",
        keywords: "chart of accounts journal ledger entries",
      },
      {
        title: "Fiscal Year",
        titleAr: "السنة المالية",
        href: "/app/fiscal-year",
        icon: CalendarClock,
        permission: "accounting.view",
        keywords: "fiscal year closing retained earnings period lock",
      },
      {
        title: "Fixed Assets",
        titleAr: "الأصول الثابتة",
        href: "/app/assets",
        icon: Boxes,
        permission: "assets.view",
        keywords: "assets depreciation fixed assets equipment",
      },
      {
        title: "Advances",
        titleAr: "سلف العملاء",
        href: "/app/advances",
        icon: HandCoins,
        permission: "advances.view",
        keywords: "advances prepayments deposits customer advances allocation",
      },
      {
        title: "Tax Reports",
        titleAr: "تقارير الضرائب",
        href: "/app/tax-reports",
        icon: Receipt,
        permission: "tax-reports.view",
        keywords: "tax reports VAT sales tax purchases tax collected paid",
      },
      {
        title: "Loyalty Points",
        titleAr: "نقاط الولاء",
        href: "/app/loyalty",
        icon: Star,
        permission: "loyalty.view",
        keywords: "loyalty points rewards customers earn redeem",
      },
      {
        title: "Budgets",
        titleAr: "الميزانيات",
        href: "/app/budgets",
        icon: PieChart,
        permission: "budgets.view",
        keywords: "budgets planning actual vs budget variance tracking",
      },
      {
        title: "Landed Costs",
        titleAr: "تكاليف الشحن",
        href: "/app/landed-costs",
        icon: Ship,
        permission: "landed-costs.view",
        keywords: "landed costs shipping handling allocation purchases",
      },
      {
        title: "Reports",
        titleAr: "التقارير",
        href: "/app/reports",
        icon: BarChart3,
        permission: "reports.view",
        keywords: "analytics statements profit loss balance sheet",
      },
    ],
  },
  {
    title: "System",
    titleAr: "النظام",
    items: [
      {
        title: "Profile",
        titleAr: "الملف الشخصي",
        href: "/app/profile",
        icon: CircleUser,
        permission: undefined,
        keywords: "profile account user name email job title role",
      },
      {
        title: "Users & Access",
        titleAr: "المستخدمون والصلاحيات",
        href: "/app/users",
        icon: Shield,
        permission: "users.view",
        superAdminOnly: true,
        keywords: "users roles permissions members team",
      },
      {
        title: "Settings",
        titleAr: "الإعدادات",
        href: "/app/settings",
        icon: Settings,
        permission: undefined,
        keywords: "preferences company profile configuration",
      },
      {
        title: "Backup & Restore",
        titleAr: "النسخ الاحتياطي والاستعادة",
        href: "/app/backup",
        icon: RotateCcw,
        permission: "backup.manage",
        keywords: "backup restore export import data safety",
      },
      {
        title: "Alerts",
        titleAr: "التنبيهات",
        href: "/app/alerts",
        icon: Siren,
        permission: "alerts.view",
        keywords: "alerts low stock overdue invoices expiring recurring",
      },
      {
        title: "Import",
        titleAr: "الاستيراد",
        href: "/app/import",
        icon: Upload,
        permission: "import.create",
        keywords: "import csv excel products parties bulk upload",
      },
      {
        title: "Currencies",
        titleAr: "العملات",
        href: "/app/currencies",
        icon: Coins,
        permission: "currencies.view",
        keywords: "currencies exchange rates forex multi currency",
      },
      {
        title: "Devices",
        titleAr: "الأجهزة",
        href: "/app/devices",
        icon: Laptop,
        permission: "network.view",
        keywords: "devices network lan wifi connect devices online",
      },
    ],
  },
];

export const NOTIFICATIONS_ROUTE = {
  title: "Notifications",
  titleAr: "الإشعارات",
  href: "/app/notifications",
  icon: Bell as LucideIcon,
  keywords: "alerts notifications bell inbox",
};

export const ALL_NAV_ITEMS = NAV_SECTIONS.flatMap((section) => [
  ...section.items,
  {
    title: NOTIFICATIONS_ROUTE.title,
    titleAr: NOTIFICATIONS_ROUTE.titleAr,
    href: NOTIFICATIONS_ROUTE.href,
    icon: NOTIFICATIONS_ROUTE.icon,
    permission: undefined,
    keywords: NOTIFICATIONS_ROUTE.keywords,
  },
]);

export function findRouteByPath(pathname: string) {
  const item = ALL_NAV_ITEMS.find((item) => item.href === pathname);
  return item ?? null;
}
